apiVersion: v1
kind: Service
metadata:
  name: {{ include "burst-scaler.fullname" . }}
  labels:
    {{- include "burst-scaler.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: grpc
      port: {{ .Values.service.port }}
      targetPort: grpc
      protocol: TCP
  selector:
    {{- include "burst-scaler.selectorLabels" . | nindent 4 }}
