apiVersion: v2
name: rabbitmq-burst-scaler
description: A KEDA external scaler for burst scaling based on RabbitMQ messages
type: application
version: 0.3.1
appVersion: "0.3.1"
keywords:
  - keda
  - rabbitmq
  - autoscaling
  - kubernetes
